version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - for url: %(url)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  movie-inventory:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]