"""empty message

Revision ID: 86357230bab4
Revises: 
Create Date: 2020-06-13 00:19:12.080673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '86357230bab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_snapshot',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=500), nullable=True),
                    sa.Column('director', sa.String(length=250), nullable=True),
                    sa.Column('release_date', sa.Date(), nullable=True),
                    sa.Column('release_year', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_snapshot')
    # ### end Alembic commands ###
